### ISSUE TITLE
NOTICE: Changes to GitHub.com have broken some parts of @reporobot 

### ISSUE THREAD

**Issue by jlord** [jlord/git-it-electron#137]
@reporobot has many jobs, one of them is to write to your repo so that you collaborate and pull in changes. 

This part is now broken because of a change to GitHub.com where you must click a button to accept becoming a collaborator in a project rather than be automatically added as it was previously. 

Thus this part of Reporobot is broken. Since it can't yet accept the invite it can't write to your repo and you can't pull in the changes.

Thus Git-it can't verify the challenge checking that you added it to your repo.

**But!** You can keep going!

### Skip It's a Small World and Pull Never Out of Date and go on to Requesting You Pull Please.

Reporobot can still merge your PR and add you to the list ✨

**Comment by xavigisbeg** [comment]
Pull Never Out of Date verified correctly my branch, as it was up to date (reporobot did not make any changes, of course). Just to know that this part works (or not, considering that my project was not contributed to) :smile: Great material!

**Comment by jlord** [comment]
I've been working on this and after a bit more testing today I hope to say that the issue is fixed ✨

**Comment by jlord** [comment]
Fixed 🎉 https://github.com/jlord/reporobot/pull/31

**Comment by jodom** [comment]
Thanks, had to dig up this issue after waiting overnight for @reporobot s contribution. @jlord ,Consider putting a note on the git-it app?

**Comment by jlord** [comment]
> overnight for @reporobot s contribution

Hmm. There is no note because this shouldn't be an issue anymore. I will find some time soon to try and see why you might be having trouble.

**Comment by jlord** [comment]
Ok, thanks so much for commenting on this issue because it was broken—for a related, but different reason. It seems the GitHub API for repository invites changed and so the invites couldn't be accepted and @reporobot couldn't then write/draw 🎨 to people's repos either. But I've fixed it now and cleared out all the pending invites 😅 Thanks again!

<img width="1082" alt="screen shot 2017-01-12 at 11 10 27 pm" src="https://cloud.githubusercontent.com/assets/1305617/21921628/5046e44a-d91e-11e6-8017-91644a66d381.png">

**Comment by jodom** [comment]
great, and I did finish the workshop😊😎 awesome. Thank you

**Comment by heatherjwright1** [comment]
Hi, 
I'm still having this issue? I'm getting a message to say reporobot needs to accept my collab invite?

**Comment by lauriemegan** [comment]
As am I!
